POST http://localhost:3003/users/signup 
Content-Type: application/json

{
	"name": "Jana",
	"email": "janaylla@gmail.com",
	"nickname": "jana",
	"password": "123456"
}
###
POST http://localhost:3003/users/login 
Content-Type: application/json

{
	"login": "janaylla@gmail.com",
	"nickname": "jana",
	"password": "123456"
}

###
POST http://localhost:3003/users/login 
Content-Type: application/json

{
	"login": "janaylla@gmail.com",
	"nickname": "jana",
	"password": "123456"
}