POST http://localhost:3003/users/signup 
Content-Type: application/json

{
	"name": "Jana",
	"email": "janaylla@gmail.com",
	"nickname": "jana",
	"password": "123456"
}
###
POST http://localhost:3003/users/login 
Content-Type: application/json

{
	"login": "janaylla@gmail.com",
	"nickname": "jana",
	"password": "123456"
}

###
POST http://localhost:3003/users/login 
Content-Type: application/json

{
	"login": "janaylla@gmail.com",
	"nickname": "jana",
	"password": "123456"
}


###
POST http://localhost:3003/tags 
Content-Type: application/json

{
	"name": "verão"
}

###
POST http://localhost:3003/collection 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxYjZiOWRkLWJiNzItNDZhZS04ZjQwLWNhZDE5Y2EzYzQ2NyIsImlhdCI6MTYyNTk0MzI0NywiZXhwIjoxNjI2MDI5NjQ3fQ.WpEYqB2j_F28KbiLFQEJueX1vaQmZBvdUT235zTAD2Q

{
	"name": "verão"
}


